#!/bin/bash
#Simple shell script to save changes and reboot a Nanostation Loco 5 via ssh 
#usage: ./ssh_save <ip_to_ssh> <ssh_username>
sshpass -f password ssh -o "StrictHostKeyChecking=no" -o KexAlgorithms=diffie-hellman-group1-sha1 -c aes128-cbc $2@$1 << EOF 
save
exit
EOF

exit 
